import { StyleSheet } from 'react-native';
import { colors, layout } from './theme';

export const dashboardStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingBottom: 20,
  },
  header: {
    backgroundColor: colors.primary,
    minHeight: 110,
    paddingHorizontal: layout.horizontalPadding,
    paddingTop: 14,
    paddingBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  brandName: {
    fontSize: 24,
    fontWeight: '800',
    color: colors.text,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    position: 'relative',
  },
  iconText: {
    fontSize: 18,
    color: colors.text,
    fontWeight: '700',
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
  },
  searchWrapper: {
    marginTop: -14,
    paddingHorizontal: layout.horizontalPadding,
    marginBottom: 14,
  },
  orderButtonWrapper: {
    paddingHorizontal: layout.horizontalPadding,
    marginBottom: 16,
  },
  orderButton: {
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: colors.text,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.white,
  },
  searchInput: {
    backgroundColor: '#FFFFFF',
    height: 42,
    borderRadius: 8,
    paddingHorizontal: 14,
    fontSize: 13,
    color: colors.text,
    borderWidth: 1,
    borderColor: '#EFEFEF',
  },
  sectionHeader: {
    paddingHorizontal: layout.horizontalPadding,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  grid: {
    paddingHorizontal: layout.horizontalPadding,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.22)',
  },
  menuPanel: {
    position: 'absolute',
    top: 72,
    right: 16,
    width: 250,
    maxHeight: 500,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingTop: 14,
    paddingHorizontal: 12,
    paddingBottom: 12,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  notificationsPanel: {
    position: 'absolute',
    top: 72,
    right: 62,
    width: 300,
    maxHeight: 420,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingTop: 14,
    paddingHorizontal: 12,
    paddingBottom: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 12,
  },
  panelList: {
    paddingBottom: 6,
  },
  panelItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 13,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  panelItemText: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
  },
  panelArrow: {
    fontSize: 18,
    color: '#9CA3AF',
  },
  languageDropdown: {
    marginTop: -2,
    marginBottom: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  languageOptionButton: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 8,
  },
  languageOptionButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  languageOptionText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
  },
  languageOptionTextActive: {
    color: colors.text,
  },
  notificationItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  notificationIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  notificationIconText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  notificationTextWrap: {
    flex: 1,
  },
  notificationTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 3,
  },
  notificationMessage: {
    fontSize: 12,
    color: colors.subtext,
    lineHeight: 16,
  },
});
